import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Run to Win Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="container mx-auto p-6 shadow-md">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-bold">RTW</h1>
          </div>
          <div className="hidden md:flex space-x-5">
            <Link href="/">
              <a>About</a>
            </Link>
            <Link href="/">
              <a>Plans</a>
            </Link>
            <Link href="/">
              <a>Contact</a>
            </Link>
          </div>
        </div>
      </nav>

      <section>
        <div className="container flex flex-col md:flex-row items-center mx-auto mt-10 px-6">
          {/* left side */}
          <div className="flex-1 flex flex-col space-y-4 py-6">
            <h1 className="max-w-md text-3xl font-extrabold text-center md:text-4xl md:text-left">
              A Transformational, Revolutionary and Holistic Fitness and
              Wellness Program designed for Christian Women
            </h1>
            <p className="max-w-md text-center text-amber-500 md:text-left">
              A program designed for Christian Women who desire fitness and
              wellness for their Spirit, Soul and Body.
              <br />1 Thessalonians 5:23a &quot;...and may your spirit and soul
              be kept complete...&quot;
            </p>
            <div className="flex justify-center md:justify-start">
              <Link href="/">
                <a className="px-6 py-3 rounded-md inline-block text-center bg-amber-600 font-medium text-white hover:bg-amber-700">
                  Get Started
                </a>
              </Link>
            </div>
          </div>

          {/* right side */}
          <div className="flex-1">
            <Image src="/images/hero.jpg" width={600} height={400} alt="" />
          </div>
        </div>
      </section>

      <section>
        <div className="container mx-auto mt-10 px-6">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
            <div className="h-30 w-30 p-3 bg-amber-300 rounded-md">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas
                officia a, expedita, sapiente velit repellendus odio pariatur
                aut ad excepturi fugit doloremque distinctio totam adipisci
                aliquam quos maxime perspiciatis repudiandae.
              </p>
            </div>
            <div className="h-30 w-30 p-3 bg-amber-300 rounded-md">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas
                officia a, expedita, sapiente velit repellendus odio pariatur
                aut ad excepturi fugit doloremque distinctio totam adipisci
                aliquam quos maxime perspiciatis repudiandae.
              </p>
            </div>
            <div className="h-30 w-30 p-3 bg-amber-300 rounded-md">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas
                officia a, expedita, sapiente velit repellendus odio pariatur
                aut ad excepturi fugit doloremque distinctio totam adipisci
                aliquam quos maxime perspiciatis repudiandae.
              </p>
            </div>
            <div className="h-30 w-30 p-3 bg-amber-300 rounded-md">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas
                officia a, expedita, sapiente velit repellendus odio pariatur
                aut ad excepturi fugit doloremque distinctio totam adipisci
                aliquam quos maxime perspiciatis repudiandae.
              </p>
            </div>
          </div>
        </div>
      </section>

      <main></main>

      <footer></footer>
    </div>
  );
}
